POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"denis", "password":"uggo"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username":"denis1", "password":"uggo", "email": "gretazu@gmail.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 19924fa9602cf113d13014e57a6f2bbe190d2ca1

{}