# Generated by Django 5.1.3 on 2024-11-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=100)),
                ('restos', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.JSONField()),
                ('cost', models.IntegerField(choices=[(0, 'Free'), (1, 'Cheap'), (2, 'Moderate'), (3, 'Expensive'), (4, 'Very Expensive')])),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('food_array', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserrFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
            ],
        ),
    ]
