# Generated by Django 5.1.3 on 2024-11-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maps',
            old_name='user',
            new_name='user_id',
        ),
    ]
