# Generated by Django 5.1.3 on 2024-11-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_restaurants_cost_restaurants_rating_foods_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='food_array',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
